config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'requests/index'
  end
  namespace :public do
    get 'requests/new'
    get 'requests/index'
  end
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

 root to: 'public/homes#top'

 namespace :admin do

  resources :genres

  resources :question_statuses

  resources :users

  resources :requests

 end


 namespace :public do

   get 'unsubscribe' => 'users#unsubscribe'
   patch 'users/withdraw'
   resources :users do
       collection do
           get 'search'
       end
   end
   resources :questions do
       resources :answers do
           resource :favorites, only: [:create, :destroy]
      end
   end
   get 'search' => 'questions#search'

   resources :requests

 end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/answer.rb
class Answer < ApplicationRecord

  has_many :favorites, dependent: :destroy

  belongs_to :user
  belongs_to :question
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  validates :answer, presence: true
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :answer

end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/question.rb
class Question < ApplicationRecord

  belongs_to :user
  belongs_to :genre
  belongs_to :question_status

  has_many :answers, dependent: :destroy

  def self.search(keyword)
  where(["title like?", "%#{keyword}%"])
  end


  validates :title, presence: true
  validates :body, presence: true
end

app/models/question_status.rb
class QuestionStatus < ApplicationRecord

  has_many :questions, dependent: :destroy

end

app/models/request.rb
class Request < ApplicationRecord

  belongs_to :user, optional: true

  validates :request, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :

  def active_for_authentication?
    super && (self.is_active == true)
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :requests, dependent: :destroy

  attachment :image

  validates :name, presence: true
  validates :introduction, presence: true



end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
 before_action :authenticate_admin!

 def index
  @genre = Genre.new
  @genres= Genre.all

 end

 def create
  @genre = Genre.new(genre_params)
  @genre.save
  redirect_to admin_genres_path
 end

 def edit
  @genre = Genre.find(params[:id])
 end

 def update
  @genre = Genre.find(params[:id])
  @genre.update(genre_params)
  redirect_to admin_genres_path
 end

  private

  def genre_params
   params.require(:genre).permit(:name)
  end

end

app/controllers/admin/requests_controller.rb
class Admin::RequestsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @requests = Request.all
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
   @users = User.all

  end

  def show
    @user =User.find(params[:id])
  end


end

app/controllers/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_users_path
    when User
      root_path
    end
  end

 protected


 def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
   devise_parameter_sanitizer.permit(:sign_up, keys: [:introduction])
   devise_parameter_sanitizer.permit(:sign_up, keys: [:image_id])

 end


end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/requests_helper.rb
module Admin::RequestsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

   # マークダウン形式で記入するためにrequire
  require "redcarpet"
  require "coderay"

  class HTMLwithCoderay < Redcarpet::Render::HTML
    def block_code(code, language)
        #language = lait('')[0]nguage.spl

        case language.to_s
        when 'rb'
            lang = 'ruby'
        when 'yml'
            lang = 'yaml'
        when 'css'
            lang = 'css'
        when 'html'
            lang = 'html'
        when ''
            lang = 'md'
        else
            lang = language
        end

        CodeRay.scan(code, lang).div
    end
  end

  # マークダウンを可能にするメソッド
  def markdown(text)
    html_render = HTMLwithCoderay.new(filter_html: true, hard_wrap: true)
    options = {
        autolink: true,
        space_after_headers: true,
        no_intra_emphasis: true,
        fenced_code_blocks: true,
        tables: true,
        hard_wrap: true,
        xhtml: true,
        lax_html_blocks: true,
        strikethrough: true
    }
    markdown = Redcarpet::Markdown.new(html_render, options)
    markdown.render(text)
  end

end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SEC</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <li><%= link_to "SEC", root_path, class:"navbar-brand" %></li>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if admin_signed_in? %>
               <li><%= link_to "ユーザー", admin_users_path,class:"fas fa-user-friends nav-link text-light" %></li>
               <li><%= link_to "ジャンル", admin_genres_path,class:"fas fa-genderless nav-link text-light" %></li>
               <li><%= link_to "質問ステータス", admin_question_statuses_path,class:"fas fa-question-circle nav-link text-light" %></li>
               <li><%= link_to "問い合わせ", admin_requests_path,class:"fas fa-head-side-cough nav-link text-light" %></li>
               <li><%= link_to "ログアウト", destroy_admin_session_path, method: :delete,class:"fas fa-sign-out-alt nav-link text-light" %></li>
              <% elsif user_signed_in? %>
               <li><%= link_to "マイページ", public_user_path(current_user.id),class:"fas fa-user nav-link text-light" %></li>
               <li><%= link_to "質問一覧", public_questions_path,class:"fas fa-question-circle nav-link text-light" %></li>
               <li><%= link_to "ユーザー", public_users_path,class:"fas fa-user-friends nav-link text-light" %></li>
               <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete,class:"fas fa-sign-out-alt nav-link text-light" %></li>
              <% else %>
               <li><%= link_to "新規登録", new_user_registration_path,class:"fas fa-user-plus nav-link text-light" %></li>
               <li><%= link_to "ログイン", new_user_session_path,class:"fas fa-sign-in-alt nav-link text-light" %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <%= yield %>
    </main>
    <footer>
        <div class="container">
        <div class="row">
          <div class="mx-auto mt-4">
           <p>
             SECについてご要望がある方はこちら⇒
             <%= link_to "クリック", new_public_request_path %>
           </p>
          </div>
        </div>
      </div>
    </footer>


  </body>
</html>